
#define DIM_X 1920
#define DIM_Y 1080
#define DIM_SCREEN_X DIM_X * 0.9
#define DIM_SCREEN_Y DIM_Y * 0.9
#define MIDLE_X DIM_SCREEN_X / 2
#define MIDLE_Y DIM_SCREEN_Y / 2
#define GRAVITY_SPEED_START 1
#define GRAVITY_MULTIPLIER 1